# Generated by Django 4.2.4 on 2023-08-31 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_subjects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subjects',
            new_name='Subject',
        ),
    ]
